spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_forum
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
    database:
      platform: org.hibernate.dialect.MySQL5Dialect

### SECRET ###
api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}